# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: "ihposey", email: "ihposey@icloud.com", password: "1234", description: "Here to save some animals!", image_url: "https://media.phish.net/hotdog.png")

Species.create(name: "Amur Leopard", latin_name: "Panthera pardus orientalis", status: "Critically Endangered", habitats: "Temperate/Mixed Forests(East Asia)", population: "84+", image_url: "https://s3.amazonaws.com/images.hamlethub.com/hh20mediafolder/1076/202005/Screen-Shot-2020-05-15-at-4.21.06-PM-1589574178.png", description: "This Beatiful Cat is highly important from and ecological and cultural standpoint. Other species thrive in their habitats.")
Species.create(name: "Black Rhino", latin_name: "Diceros bicornis", status: "Critically Endangered", habitats: "Semi-Desert Savannah, Woodlands, Forests, Wetlands", population: "5600+", image_url: "https://static.insider.com/image/5d765fad6f24eb0f3a63dbf3.jpg", description: "Rhinos are some of the oldest mammals on the planet. Rhinos play a huge part in tourism in Namibia.")
Species.create(name: "Spectacled Bear", latin_name: "Tremarctos Ornatus", status: "Vulnerabe", habitats: "Neotropic, cloud forests(South American Andes)", population: "6,000 to 10,000", image_url: "https://www.bearbiology.org/wp-content/uploads/2017/12/shutterstock_161735486.jpg", description: "Spectacled bears are the only surviving species of bear native to South America and last remaining short faced bear. The species has become fragmented over the last century and their habitat has become heavily influenced by humans, due to habitat destruction degredation and hunting/poaching.")
Species.create(name: "Red Panda", latin_name: "Ailurus Fulgens", status: "Endangered", habitats: "Temperate Forests (Eastern Himilayas)", population: "less than 10,000", image_url: "https://images.theconversation.com/files/317421/original/file-20200226-24651-1or3uxq.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=675.0&fit=crop", description: "About 50% of the Red Pandas habitat exists only in the Eastern Himilayas. Due to increased loss of bamboo and nesting trees caused by deforestation, these acrobatic tree dwellers are losing their home and food source causing a rapid decline in their population.")
Species.create(name: "Vaquita", latin_name: "Phocoena Sinus", status: "Critically Endangered", habitats: "Marine Habitat (Northern Gulf Of California", population: "10", image_url: "https://sites.google.com/a/wornickjds.org/endangered-animals-class-of-2021/_/rsrc/1433528765948/home/vaquita-dolphin/habitat.jpg", description: "Now considered the rarest marine mammal the unique coloring of the Vaquita sets it apart from similar species. Often caught by illegal fishing operations within protected marine areas on Mexicos gulf of California, their population has nearly diminished leaving only double digits remaining.")
Species.create(name: "Polar Bear", latin_name: "Ursus Maritimus", status: "Vulnerable", habitats: "Arctic Ocean, sea ice and adjacent coastal areas", population: "22,000+", image_url: "https://cdn.audleytravel.com/3994/2849/79/1340901-polar-bear-churchill.jpg", description: "Polar bears are not only the largest bear in the World, but rank as the Arctics top predator. With global warming shrinking the length of their winter and receeding their habitat melting the ice, these massive creatures who rely heavily on ice for travel, mating, and hunting food are losing their home and being driven into human populated areas.")
Species.create(name: "Galapagos Penguin", latin_name: "Sphenicus Mendiculus", status: "Endangered", habitats: "Ocean Habitat (Ocean Habitat (North of the equator", population: "less than 2,000", image_url: "https://penguin-pedia.com/wp-content/uploads/2019/06/Galapagos-4.jpg", description: "Galapagos penguins are the only penguin species found north of the equator. This unique species is threatened by increasing pollution, bycatch and climate change running their population dangerously low.")
Species.create(name: "Black Spider Monkey", latin_name: "Ateles Paniscus", status: "Vulnerable", habitats: "Tropical and Subtropical forests (moist broadleaf forests)", population: "Unknown", image_url: "https://upload.wikimedia.org/wikipedia/commons/8/84/Ateles_fusciceps_Colombia.JPG", description: "One of the largest primate species in South America, these rainforest dwellers are an essential part of their tropical ecosystem. Their key role in seed dispersal allows the forests they inhabit to grow and thrive. Poaching and the destruction of rainforests encorach on their survival.")
Species.create(name: "Hawksbill Turtle", latin_name: "Eretmochelys Imbriticata", status: "Critically Endangered", habitats: "Tropical Oceans", population: "approx 8,000 nesting females", image_url: "https://img-cdn.greatergood.com/clickToGive/images/takeaction/campaigns/hawksbill-sea-turtle.jpg", description: "Hawkbills are a fundamental link in marine ecosystems. To help maintain the health of seagrass beds and coral reefs, Hawksbills use their distinct narrow beaks to feed mainly on destructive sponges they extract from narrow crevices o the reef. With uniquely colored shells, they are often poached to be sold in markets. This increased poaching has left a mere 8,000 nesting (fertile) females worldwide.")
Species.create(name: "Bonobo", latin_name: "Pan Paniscus", status: "Endangered", habitats: "Forests", population: "10,000 to 50,000", image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Apeldoorn_Apenheul_zoo_Bonobo.jpg", description: "Bonobos are the last great ape to be scientifically described, leaving much unknown about this subspecies. Wild bonobos can only be found South of the Congo river in DRC forests. Poverty and civil unrest surrounding the Bonobos habitat have contributed to mass poaching and deforestation. With low reproductive rates and growing threats scientists believe the population is at risk for continued rapid decline.")
Species.create(name: "Sunbear", latin_name: "Helarctos Malayanus", status: "Vulnerable", habitats: "Tropical forests (South Asia)", population: "No reliable population figures", image_url: "https://preview.redd.it/2u1jdlx92mr41.jpg?auto=webp&s=1c6c08879effd1ed0e8bafabb91face2a3491d3e", description: "Named for their prominent golden crest patch, sunbears are the smallest bear species known. With such a small habitat/population area and increased threats caused by heavy deforestation and illegal hunting, their global population is estimated to have decreased by 35% in the last 3 decades categorizing this unique species as vulnerable.")
Species.create(name: "Mountain Gorilla", latin_name: "Gorilla Beringei beringei", status: "Endangered", habitats: "Forests, Mountains (Congo Basin)", population: "1000+", image_url: "https://c402277.ssl.cf1.rackcdn.com/photos/18330/images/hero_small/Mountain_Gorilla_Silverback_WW22557.jpg?1576515753", description: "Since their discovery as a subspecies of the Eastern Gorilla in 1902, Mountain Gorillas have endured war, hunting, disease, ad habitat destruction. These threats came so severe, it was estimated this species would be extinct by the end of the twentieth century. However recent conservation efforts have been successful increasing the population from 480 individuals to over 1,000 individuals since 2010.")